version: "3.7"
services:
  otel:
    image: amazon/aws-otel-collector:latest
    command: --config /config/collector-config.yml --log-level debug
    volumes:
      - .:/config
      - ~/.aws:/root/.aws
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
    ports:
      - '4317:4317'

  app:
    image: ${APP_IMAGE}
    environment:
      - INSTANCE_ID
      - LISTEN_ADDRESS
      - OTEL_RESOURCE_ATTRIBUTES=service.name=aws-otel-integ-test
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel:4317
    ports:
      - '4567:4567'
      - '8080:8080'

  validator:
    image: public.ecr.aws/u0d6r4y4/aws-otel-test-validator:alpha
    command: ${VALIDATOR_COMMAND}
    depends_on:
      - otel
      - app
    volumes:
      - ~/.aws:/root/.aws
    environment:
      - AWS_REGION=us-west-2
