## This workflow aims to run the Application Signals end-to-end tests to test changes
## on the E2E testing resources before submitting a PR. The e2e-eks-test will deploy a
## sample app on an EKS cluster, call the APIs, and validate the generated telemetry
## including logs, metrics, and traces while the e2e-ec2-test will do the same but on
## two EC2 instances.#
name: Test
on:
  push:

jobs:
  e2e-eks-test:
    uses: ./.github/workflows/appsignals-e2e-eks-test.yml
    secrets: inherit
    with:
      aws-region: us-east-1
      test-cluster-name: GithubTest
      caller-workflow-name: 'test'

  e2e-ec2-test:
    uses: ./.github/workflows/appsignals-e2e-ec2-test.yml
    secrets: inherit
    with:
      aws-region: us-east-1
      caller-workflow-name: 'test'
